Libraries import

In [237]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics

Data collection

In [238]:
df = pd.read_csv("Data/Car details v3.csv")

In [239]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [240]:
df.shape

(8128, 13)

In [241]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [243]:
df.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [244]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [245]:
df.duplicated().sum()

np.int64(1202)

In [246]:
df[df.duplicated()].head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
291,Hyundai Grand i10 Sportz,2017,450000,35000,Petrol,Individual,Manual,First Owner,18.9 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0
296,Maruti Swift VXI,2012,330000,50000,Petrol,Individual,Manual,Second Owner,18.6 kmpl,1197 CC,85.8 bhp,114Nm@ 4000rpm,5.0
370,Jaguar XE 2016-2019 2.0L Diesel Prestige,2017,2625000,9000,Diesel,Dealer,Automatic,First Owner,13.6 kmpl,1999 CC,177 bhp,430Nm@ 1750-2500rpm,5.0
371,Lexus ES 300h,2019,5150000,20000,Petrol,Dealer,Automatic,First Owner,22.37 kmpl,2487 CC,214.56 bhp,202Nm@ 3600-5200rpm,5.0
372,Jaguar XF 2.0 Diesel Portfolio,2017,3200000,45000,Diesel,Dealer,Automatic,First Owner,19.33 kmpl,1999 CC,177 bhp,430Nm@ 1750-2500rpm,5.0

In [247]:
print("Total rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())
print("Unique rows:", df.drop_duplicates().shape[0])

Total rows: 8128
Duplicate rows: 1202
Unique rows: 6926

In [248]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing[missing["Missing Values"] > 0]

           Missing Values  Percentage
mileage               221    2.718996
engine                221    2.718996
max_power             215    2.645177
torque                222    2.731299
seats                 221    2.718996

In [249]:
df_clean = df.drop_duplicates().copy()

In [250]:
print("Original dataset:", df.shape)
print("Cleaned dataset:", df_clean.shape)
print("Remaining duplicates:", df_clean.duplicated().sum())

Original dataset: (8128, 13)
Cleaned dataset: (6926, 13)
Remaining duplicates: 0

In [251]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6926 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   year           6926 non-null   int64
 2   selling_price  6926 non-null   int64
 3   km_driven      6926 non-null   int64
 4   fuel           6926 non-null   object
 5   seller_type    6926 non-null   object
 6   transmission   6926 non-null   object
 7   owner          6926 non-null   object
 8   mileage        6718 non-null   object
 9   engine         6718 non-null   object
 10  max_power      6721 non-null   object
 11  torque         6717 non-null   object
 12  seats          6718 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 757.5+ KB

In [252]:
columns = ['mileage', 'engine', 'max_power', 'torque', 'seats']

for col in columns:
    print(f"\n{col}:")
    print(df_clean[col].dropna().head(5).tolist())

mileage:
['23.4 kmpl', '21.14 kmpl', '17.7 kmpl', '23.0 kmpl', '16.1 kmpl']

engine:
['1248 CC', '1498 CC', '1497 CC', '1396 CC', '1298 CC']

max_power:
['74 bhp', '103.52 bhp', '78 bhp', '90 bhp', '88.2 bhp']

torque:
['190Nm@ 2000rpm', '250Nm@ 1500-2500rpm', '12.7@ 2,700(kgm@ rpm)', '22.4 kgm at 1750-2750rpm', '11.5@ 4,500(kgm@ rpm)']

seats:
[5.0, 5.0, 5.0, 5.0, 5.0]

In [253]:
df_clean['mileage'].dropna().str.extract(
    r'([a-zA-Z/]+)$'
)[0].value_counts()

0
kmpl     6631
km/kg      87
Name: count, dtype: int64

In [254]:
# Extract numerical values from engine
df_clean['engine'] = pd.to_numeric(
    df_clean['engine'].str.extract(r'(\d+\.?\d*)')[0]
)

# Extract numerical values from max_power
df_clean['max_power'] = pd.to_numeric(
    df_clean['max_power'].str.extract(r'(\d+\.?\d*)')[0]
)

In [255]:
df_clean['mileage'] = pd.to_numeric(
    df_clean['mileage'].str.extract(r'(\d+\.?\d*)')[0]
)

In [256]:
df_clean[['mileage', 'engine', 'max_power']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 6926 entries, 0 to 8125
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mileage    6718 non-null   float64
 1   engine     6718 non-null   float64
 2   max_power  6720 non-null   float64
dtypes: float64(3)
memory usage: 216.4 KB

In [257]:
df_clean[['mileage', 'engine', 'max_power']].head(10)

   mileage  engine  max_power
0    23.40  1248.0      74.00
1    21.14  1498.0     103.52
2    17.70  1497.0      78.00
3    23.00  1396.0      90.00
4    16.10  1298.0      88.20
5    20.14  1197.0      81.86
6    17.30  1061.0      57.50
7    16.10   796.0      37.00
8    23.59  1364.0      67.10
9    20.00  1399.0      68.10

In [258]:
df['torque'].dropna().head(20).tolist()

['190Nm@ 2000rpm',
 '250Nm@ 1500-2500rpm',
 '12.7@ 2,700(kgm@ rpm)',
 '22.4 kgm at 1750-2750rpm',
 '11.5@ 4,500(kgm@ rpm)',
 '113.75nm@ 4000rpm',
 '7.8@ 4,500(kgm@ rpm)',
 '59Nm@ 2500rpm',
 '170Nm@ 1800-2400rpm',
 '160Nm@ 2000rpm',
 '248Nm@ 2250rpm',
 '78Nm@ 4500rpm',
 '190Nm@ 2000rpm',
 '84Nm@ 3500rpm',
 '115Nm@ 3500-3600rpm',
 '200Nm@ 1750rpm',
 '22.4 kgm at 1750-2750rpm',
 '62Nm@ 3000rpm',
 '219.7Nm@ 1500-2750rpm',
 '160Nm@ 2000rpm']

In [259]:
print("Nm values:",
      df['torque'].str.contains('Nm', case=False, na=False).sum())

print("kgm values:",
      df['torque'].str.contains('kgm', case=False, na=False).sum())

Nm values: 7390
kgm values: 505

In [260]:
df['mileage'].dropna().str.extract(
    r'([a-zA-Z/]+)\s*$'
)[0].value_counts()

0
kmpl     7819
km/kg      88
Name: count, dtype: int64

In [261]:
print("Nm examples:")

print(
    df_clean[
        df_clean['torque'].str.contains(
            'Nm', case=False, na=False
        )
    ]['torque'].head(10).tolist()
)

Nm examples:
['190Nm@ 2000rpm', '250Nm@ 1500-2500rpm', '113.75nm@ 4000rpm', '59Nm@ 2500rpm', '170Nm@ 1800-2400rpm', '160Nm@ 2000rpm', '248Nm@ 2250rpm', '78Nm@ 4500rpm', '190Nm@ 2000rpm', '84Nm@ 3500rpm']

In [262]:
print("kgm examples:")

print(
    df_clean[
        df_clean['torque'].str.contains(
            'kgm', case=False, na=False
        )
    ]['torque'].head(10).tolist()
)

kgm examples:
['12.7@ 2,700(kgm@ rpm)', '22.4 kgm at 1750-2750rpm', '11.5@ 4,500(kgm@ rpm)', '7.8@ 4,500(kgm@ rpm)', '22.4 kgm at 1750-2750rpm', '6.1kgm@ 3000rpm', '6.1kgm@ 3000rpm', '13.1kgm@ 4600rpm', '14.9 KGM at 3000 RPM', '11.4 kgm at 4,000 rpm']

In [263]:
mask = (
    df_clean['torque'].notna() &
    ~df_clean['torque'].str.contains(
        r'Nm|kgm', case=False, na=False
    )
)

df_clean.loc[mask, 'torque'].value_counts()

torque
210 / 1900           7
250@ 1250-5000rpm    1
510@ 1600-2400       1
110(11.2)@ 4800      1
Name: count, dtype: int64

In [264]:
df_clean.loc[mask, ['name', 'year', 'torque']]

                                     name  year             torque
140            Skoda Superb LK 1.8 TSI AT  2018  250@ 1250-5000rpm
1676  Mercedes-Benz M-Class ML 350 4Matic  2011     510@ 1600-2400
2000     Honda Jazz Select Edition Active  2011    110(11.2)@ 4800
4373     Skoda Octavia Classic 1.9 TDI MT  2006         210 / 1900
5572     Skoda Octavia Classic 1.9 TDI MT  2007         210 / 1900
5785    Skoda Octavia Ambiente 1.9 TDI MT  2007         210 / 1900
6418    Skoda Octavia Ambiente 1.9 TDI MT  2003         210 / 1900
7154       Skoda Octavia Rider 1.9 AT TDI  2008         210 / 1900
7296       Skoda Octavia Ambiente 1.9 TDI  2010         210 / 1900
7532    Skoda Octavia Ambiente 1.9 TDI MT  2007         210 / 1900

In [265]:
import re

In [266]:
def convert_torque(value):

    if pd.isna(value):
        return np.nan

    value = str(value).lower().replace(',', '')

    number = re.search(r'\d+\.?\d*', value)

    if number is None:
        return np.nan

    torque = float(number.group())

    # Explicit Nm notation
    if 'nm' in value:
        return torque

    # Explicit kgm notation with plausible torque values
    if 'kgm' in value and torque <= 50:
        return torque * 9.80665

    # Ambiguous formats: don't guess
    return np.nan

In [267]:
df_clean['torque_nm'] = df_clean['torque'].apply(convert_torque)

In [268]:
df_clean.nlargest(10, 'torque_nm')[
    ['name', 'torque', 'torque_nm']
]

                                  name               torque  torque_nm
951                       Maruti Zen D       789Nm@ 2250rpm      789.0
4720                      Maruti Zen D       789Nm@ 2250rpm      789.0
5143                      Maruti Zen D       789Nm@ 2250rpm      789.0
170      Volvo XC90 T8 Excellence BSIV       640Nm@ 1740rpm      640.0
136    Mercedes-Benz S-Class S 350 CDI  620Nm@ 1600-2400rpm      620.0
1071  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
2938             BMW X7 xDrive 30d DPE  620Nm@ 1500-2500rpm      620.0
4753  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
4766  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
6258  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0

In [269]:
df_clean[['torque', 'torque_nm']].head(20)

                      torque   torque_nm
0             190Nm@ 2000rpm  190.000000
1        250Nm@ 1500-2500rpm  250.000000
2      12.7@ 2,700(kgm@ rpm)  124.544455
3   22.4 kgm at 1750-2750rpm  219.668960
4      11.5@ 4,500(kgm@ rpm)  112.776475
5          113.75nm@ 4000rpm  113.750000
6       7.8@ 4,500(kgm@ rpm)   76.491870
7              59Nm@ 2500rpm   59.000000
8        170Nm@ 1800-2400rpm  170.000000
9             160Nm@ 2000rpm  160.000000
10            248Nm@ 2250rpm  248.000000
11             78Nm@ 4500rpm   78.000000
12            190Nm@ 2000rpm  190.000000
13                       NaN         NaN
14             84Nm@ 3500rpm   84.000000
15       115Nm@ 3500-3600rpm  115.000000
16            200Nm@ 1750rpm  200.000000
17  22.4 kgm at 1750-2750rpm  219.668960
18             62Nm@ 3000rpm   62.000000
19     219.7Nm@ 1500-2750rpm  219.700000

In [270]:
df_clean.loc[mask, ['name', 'torque', 'torque_nm']]

                                     name             torque  torque_nm
140            Skoda Superb LK 1.8 TSI AT  250@ 1250-5000rpm        NaN
1676  Mercedes-Benz M-Class ML 350 4Matic     510@ 1600-2400        NaN
2000     Honda Jazz Select Edition Active    110(11.2)@ 4800        NaN
4373     Skoda Octavia Classic 1.9 TDI MT         210 / 1900        NaN
5572     Skoda Octavia Classic 1.9 TDI MT         210 / 1900        NaN
5785    Skoda Octavia Ambiente 1.9 TDI MT         210 / 1900        NaN
6418    Skoda Octavia Ambiente 1.9 TDI MT         210 / 1900        NaN
7154       Skoda Octavia Rider 1.9 AT TDI         210 / 1900        NaN
7296       Skoda Octavia Ambiente 1.9 TDI         210 / 1900        NaN
7532    Skoda Octavia Ambiente 1.9 TDI MT         210 / 1900        NaN

In [271]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6926 entries, 0 to 8125
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   year           6926 non-null   int64
 2   selling_price  6926 non-null   int64
 3   km_driven      6926 non-null   int64
 4   fuel           6926 non-null   object
 5   seller_type    6926 non-null   object
 6   transmission   6926 non-null   object
 7   owner          6926 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6720 non-null   float64
 11  torque         6717 non-null   object
 12  seats          6718 non-null   float64
 13  torque_nm      6684 non-null   float64
dtypes: float64(5), int64(3), object(6)
memory usage: 811.6+ KB

In [272]:
df_clean.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          208
engine           208
max_power        206
torque           209
seats            208
torque_nm        242
dtype: int64

In [273]:
df_clean[['mileage', 'engine', 'max_power',
          'torque_nm', 'seats']].describe()

          mileage       engine    max_power    torque_nm        seats
count  6718.00000  6718.000000  6720.000000  6684.000000  6718.000000
mean     19.46531  1430.891337    87.726919   170.870219     5.434653
std       4.04915   493.493277    31.771619    84.440761     0.984230
min       0.00000   624.000000     0.000000    47.071920     2.000000
25%      16.80000  1197.000000    67.100000   110.000000     5.000000
50%      19.44000  1248.000000    81.830000   160.000000     5.000000
75%      22.50000  1498.000000   100.000000   200.055660     5.000000
max      42.00000  3604.000000   400.000000   789.000000    14.000000

In [274]:
print("Zero mileage:",
      (df_clean['mileage'] == 0).sum())

print("Zero engine:",
      (df_clean['engine'] == 0).sum())

print("Zero max power:",
      (df_clean['max_power'] == 0).sum())

Zero mileage: 15
Zero engine: 0
Zero max power: 3

In [275]:
df_clean.nlargest(10, 'torque_nm')[
    ['name', 'year', 'torque', 'torque_nm']
]

                                  name  year               torque  torque_nm
951                       Maruti Zen D  2003       789Nm@ 2250rpm      789.0
4720                      Maruti Zen D  2002       789Nm@ 2250rpm      789.0
5143                      Maruti Zen D  2006       789Nm@ 2250rpm      789.0
170      Volvo XC90 T8 Excellence BSIV  2017       640Nm@ 1740rpm      640.0
136    Mercedes-Benz S-Class S 350 CDI  2017  620Nm@ 1600-2400rpm      620.0
1071  BMW 6 Series GT 630d Luxury Line  2018  620Nm@ 2000-2500rpm      620.0
2938             BMW X7 xDrive 30d DPE  2020  620Nm@ 1500-2500rpm      620.0
4753  BMW 6 Series GT 630d Luxury Line  2018  620Nm@ 2000-2500rpm      620.0
4766  BMW 6 Series GT 630d Luxury Line  2018  620Nm@ 2000-2500rpm      620.0
6258  BMW 6 Series GT 630d Luxury Line  2018  620Nm@ 2000-2500rpm      620.0

In [276]:
df_clean.nlargest(10, 'max_power')[
    ['name', 'year', 'max_power']
]

                                      name  year  max_power
170          Volvo XC90 T8 Excellence BSIV  2017      400.0
148        Mercedes-Benz S-Class S 350 CDI  2017      282.0
134        Jeep Wrangler 2016-2019 3.6 4X4  2017      280.0
5962     Mercedes-Benz E-Class E350 Petrol  2009      272.0
2826  Jaguar XF 3.0 Litre S Premium Luxury  2014      270.9
4787                      Jaguar XF Diesel  2015      270.9
5823  Jaguar XF 3.0 Litre S Premium Luxury  2016      270.9
2938                 BMW X7 xDrive 30d DPE  2020      265.0
1071      BMW 6 Series GT 630d Luxury Line  2018      261.4
4753      BMW 6 Series GT 630d Luxury Line  2018      261.4

In [277]:
df_clean['seats'].value_counts().sort_index()

seats
2.0        2
4.0      124
5.0     5254
6.0       57
7.0      966
8.0      222
9.0       74
10.0      18
14.0       1
Name: count, dtype: int64

In [278]:
df_clean['torque_nm'] = df_clean['torque'].apply(convert_torque)

In [279]:
df_clean.nlargest(10, 'torque_nm')[
    ['name', 'torque', 'torque_nm']
]

                                  name               torque  torque_nm
951                       Maruti Zen D       789Nm@ 2250rpm      789.0
4720                      Maruti Zen D       789Nm@ 2250rpm      789.0
5143                      Maruti Zen D       789Nm@ 2250rpm      789.0
170      Volvo XC90 T8 Excellence BSIV       640Nm@ 1740rpm      640.0
136    Mercedes-Benz S-Class S 350 CDI  620Nm@ 1600-2400rpm      620.0
1071  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
2938             BMW X7 xDrive 30d DPE  620Nm@ 1500-2500rpm      620.0
4753  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
4766  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
6258  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0

In [280]:
df_clean[df_clean['seats'] == 14][
    ['name', 'year', 'seats']
]

                                         name  year  seats
4575  Tata Winger Deluxe - Flat Roof (Non-AC)  2010   14.0

In [281]:
df_clean[
    (df_clean['mileage'] == 0) |
    (df_clean['max_power'] == 0)
][['name', 'year', 'mileage', 'max_power']]

,name,year,mileage,max_power
575,Maruti Alto K10 LXI,2011,NaN,0.00
644,Tata Indica Vista Aura Safire Anniversary Edition,2009,0.0,65.00
785,Hyundai Santro Xing GL,2009,0.0,62.00
1442,Maruti Swift Dzire VDI Optional,2017,NaN,0.00
1649,Hyundai Santro Xing GL,2008,0.0,62.00
1676,Mercedes-Benz M-Class ML 350 4Matic,2011,0.0,165.00
2137,Land Rover Freelander 2 TD4 HSE,2013,0.0,115.00
2366,Hyundai Santro Xing (Non-AC),2010,0.0,62.10
2549,Tata Indica Vista Quadrajet LS,2012,NaN,0.00
2725,Hyundai Santro Xing (Non-AC),2013,0.0,62.10
5276,Hyundai Santro Xing GL,2008,0.0,62.00
5843,Volkswagen Polo GT TSI BSIV,2014,0.0,103.25
5846,Volkswagen Polo GT TSI BSIV,2014,0.0,103.25
5900,Mahindra Bolero Pik-Up FB 1.7T,2020,0.0,70.00
6534,Hyundai Santro Xing GL,2010,0.0,62.00
6629,Mahindra Bolero Pik-Up CBC 1.7T,2019,0.0,70.00
6824,Hyundai Santro Xing GL,2011,0.0,62.00
7337,Mercedes-Benz GLC 220d 4MATIC,2017,0.0,194.00

In [282]:
df_clean.loc[df_clean['mileage'] == 0, 'mileage'] = np.nan

df_clean.loc[df_clean['max_power'] == 0, 'max_power'] = np.nan

In [286]:
print("Zero mileage:",
      (df_clean['mileage'] == 0).sum())

print("Zero max power:",
      (df_clean['max_power'] == 0).sum())

print("Missing mileage:",
      df_clean['mileage'].isnull().sum())

print("Missing max power:",
      df_clean['max_power'].isnull().sum())

Zero mileage: 0
Zero max power: 0
Missing mileage: 223
Missing max power: 209

In [232]:
df_clean[df_clean['torque_nm'] > 700][
    ['name', 'year', 'torque', 'torque_nm']
]

Empty DataFrame
Columns: [name, year, torque, torque_nm]
Index: []

In [233]:
df.loc[df_clean.index[df_clean['torque_nm'] > 700], 'torque']

Series([], Name: torque, dtype: object)

In [234]:
print("Total missing torque:",
      df_clean['torque_nm'].isnull().sum())

print("Total valid torque:",
      df_clean['torque_nm'].notnull().sum())

Total missing torque: 245
Total valid torque: 6681

In [235]:
df_clean.loc[
    df_clean['torque_nm'] > 700,
    'torque_nm'
] = np.nan

In [236]:
missing_torque = df_clean[df_clean['torque_nm'].isnull()]

print("Total missing torque:",
      len(missing_torque))

print("\nOriginal torque values:")

print(
    missing_torque['torque']
    .value_counts()
    .head(25)
)

Total missing torque: 245

Original torque values:
torque
145@ 4,100(kgm@ rpm)         10
210 / 1900                    7
115@ 2,500(kgm@ rpm)          4
130@ 2500(kgm@ rpm)           4
789Nm@ 2250rpm                3
510@ 1600-2400                1
250@ 1250-5000rpm             1
110(11.2)@ 4800               1
115@ 2500(kgm@ rpm)           1
110@ 3,000(kgm@ rpm)          1
190@ 21,800(kgm@ rpm)         1
51@ 1,750-3,000(kgm@ rpm)     1
53@ 2,000-2,750(kgm@ rpm)     1
Name: count, dtype: int64

In [287]:
print("Total records:", len(df_clean))

print("Missing torque:",
      df_clean['torque_nm'].isnull().sum())

print("Valid torque:",
      df_clean['torque_nm'].notnull().sum())

Total records: 6926
Missing torque: 242
Valid torque: 6684

In [288]:
df_clean[['torque', 'torque_nm']].head(30)

                      torque   torque_nm
0             190Nm@ 2000rpm  190.000000
1        250Nm@ 1500-2500rpm  250.000000
2      12.7@ 2,700(kgm@ rpm)  124.544455
3   22.4 kgm at 1750-2750rpm  219.668960
4      11.5@ 4,500(kgm@ rpm)  112.776475
5          113.75nm@ 4000rpm  113.750000
6       7.8@ 4,500(kgm@ rpm)   76.491870
7              59Nm@ 2500rpm   59.000000
8        170Nm@ 1800-2400rpm  170.000000
9             160Nm@ 2000rpm  160.000000
10            248Nm@ 2250rpm  248.000000
11             78Nm@ 4500rpm   78.000000
12            190Nm@ 2000rpm  190.000000
13                       NaN         NaN
14             84Nm@ 3500rpm   84.000000
15       115Nm@ 3500-3600rpm  115.000000
16            200Nm@ 1750rpm  200.000000
17  22.4 kgm at 1750-2750rpm  219.668960
18             62Nm@ 3000rpm   62.000000
19     219.7Nm@ 1500-2750rpm  219.700000
20            160Nm@ 2000rpm  160.000000
21            200Nm@ 1750rpm  200.000000
22            190Nm@ 2000rpm  190.000000
23            200Nm@ 1750rpm  200.000000
24            114Nm@ 3500rpm  114.000000
25            115Nm@ 4000rpm  115.000000
26             69Nm@ 3500rpm   69.000000
27          172.5Nm@ 1750rpm  172.500000
28             84Nm@ 3500rpm   84.000000
29             59Nm@ 2500rpm   59.000000

In [289]:
df_clean.nlargest(10, 'torque_nm')[
    ['name', 'torque', 'torque_nm']
]

                                  name               torque  torque_nm
951                       Maruti Zen D       789Nm@ 2250rpm      789.0
4720                      Maruti Zen D       789Nm@ 2250rpm      789.0
5143                      Maruti Zen D       789Nm@ 2250rpm      789.0
170      Volvo XC90 T8 Excellence BSIV       640Nm@ 1740rpm      640.0
136    Mercedes-Benz S-Class S 350 CDI  620Nm@ 1600-2400rpm      620.0
1071  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
2938             BMW X7 xDrive 30d DPE  620Nm@ 1500-2500rpm      620.0
4753  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
4766  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0
6258  BMW 6 Series GT 630d Luxury Line  620Nm@ 2000-2500rpm      620.0

In [290]:
df_clean.loc[
    df_clean['torque_nm'] > 700,
    'torque_nm'
] = np.nan

In [291]:
df_clean.nlargest(10, 'torque_nm')[
    ['name', 'torque', 'torque_nm']
]

,name,torque,torque_nm
170,Volvo XC90 T8 Excellence BSIV,640Nm@ 1740rpm,640.0
136,Mercedes-Benz S-Class S 350 CDI,620Nm@ 1600-2400rpm,620.0
1071,BMW 6 Series GT 630d Luxury Line,620Nm@ 2000-2500rpm,620.0
2938,BMW X7 xDrive 30d DPE,620Nm@ 1500-2500rpm,620.0
4753,BMW 6 Series GT 630d Luxury Line,620Nm@ 2000-2500rpm,620.0
4766,BMW 6 Series GT 630d Luxury Line,620Nm@ 2000-2500rpm,620.0
6258,BMW 6 Series GT 630d Luxury Line,620Nm@ 2000-2500rpm,620.0
2705,Mercedes-Benz M-Class ML 350 CDI,619Nm@ 1600-2400rpm,619.0
7506,Mercedes-Benz GL-Class 350 CDI Blue Efficiency,619Nm@ 1600-2400rpm,619.0
7808,Mercedes-Benz M-Class ML 350 CDI,619Nm@ 1600-2400rpm,619.0

In [292]:
print("Missing torque:",
      df_clean['torque_nm'].isnull().sum())

print("Valid torque:",
      df_clean['torque_nm'].notnull().sum())

Missing torque: 245
Valid torque: 6681

In [293]:
missing_torque = df_clean[
    df_clean['torque_nm'].isnull()
]

missing_torque['torque'].value_counts().head(20)

torque
145@ 4,100(kgm@ rpm)         10
210 / 1900                    7
115@ 2,500(kgm@ rpm)          4
130@ 2500(kgm@ rpm)           4
789Nm@ 2250rpm                3
510@ 1600-2400                1
250@ 1250-5000rpm             1
110(11.2)@ 4800               1
115@ 2500(kgm@ rpm)           1
110@ 3,000(kgm@ rpm)          1
190@ 21,800(kgm@ rpm)         1
51@ 1,750-3,000(kgm@ rpm)     1
53@ 2,000-2,750(kgm@ rpm)     1
Name: count, dtype: int64

In [294]:
missing_torque = df_clean[
    df_clean['torque_nm'].isnull()
].copy()

missing_torque['first_number'] = (
    missing_torque['torque']
    .str.extract(r'(\d+\.?\d*)')
    .astype(float)
)

missing_torque[
    ['name', 'year', 'torque', 'first_number']
].head(30)

,name,year,torque,first_number
13,Maruti Swift 1.3 VXi,2007,NaN,NaN
31,Fiat Palio 1.2 ELX,2003,NaN,NaN
78,Tata Indica DLS,2003,NaN,NaN
87,Maruti Swift VDI BSIV W ABS,2015,NaN,NaN
119,Maruti Swift VDI BSIV,2010,NaN,NaN
138,BMW X1 sDrive 20D xLine,2017,NaN,NaN
140,Skoda Superb LK 1.8 TSI AT,2018,250@ 1250-5000rpm,250.0
200,Toyota Etios GD,2012,NaN,NaN
206,Maruti Omni E 8 Str STD,2003,NaN,NaN
228,Maruti Swift 1.3 VXi,2008,NaN,NaN
252,Tata Indica DLS,2005,NaN,NaN
306,Maruti Swift 1.3 VXi,2010,NaN,NaN
316,Mahindra Willys CJ 3B 4X4,1983,NaN,NaN
336,Hyundai Santro Xing XL,2005,NaN,NaN
390,Toyota Etios Liva Diesel TRD Sportivo,2012,NaN,NaN
516,Maruti Swift VDI BSIV,2010,NaN,NaN
535,Maruti Estilo LXI,2010,NaN,NaN
539,Maruti Swift VDI BSIV,2008,NaN,NaN
575,Maruti Alto K10 LXI,2011,NaN,NaN
604,Tata Sumo CX 10 Str BSIV,2011,"115@ 2,500(kgm@ rpm)",115.0
688,Hyundai Santro Xing XG,2006,NaN,NaN
725,Toyota Etios GD,2012,NaN,NaN
743,Maruti Swift 1.3 VXi,2006,NaN,NaN
744,Mahindra Bolero GLX,2004,NaN,NaN
747,Maruti Zen Estilo VXI BSIV W ABS,2011,NaN,NaN
756,Hyundai Santro Xing XP,2003,NaN,NaN
774,Hyundai Santro GLS I - Euro I,1999,NaN,NaN
776,Skoda Superb 1.8 TSI,2010,NaN,NaN
862,Maruti Esteem Vxi - BSII,2005,NaN,NaN
951,Maruti Zen D,2003,789Nm@ 2250rpm,789.0

In [295]:
missing_torque['torque'].value_counts().head(30)

torque
145@ 4,100(kgm@ rpm)         10
210 / 1900                    7
115@ 2,500(kgm@ rpm)          4
130@ 2500(kgm@ rpm)           4
789Nm@ 2250rpm                3
510@ 1600-2400                1
250@ 1250-5000rpm             1
110(11.2)@ 4800               1
115@ 2500(kgm@ rpm)           1
110@ 3,000(kgm@ rpm)          1
190@ 21,800(kgm@ rpm)         1
51@ 1,750-3,000(kgm@ rpm)     1
53@ 2,000-2,750(kgm@ rpm)     1
Name: count, dtype: int64

In [296]:
# Original torque is genuinely missing
genuine_missing = df_clean['torque'].isnull().sum()

# Original torque exists, but conversion failed
unparsed = (
    df_clean['torque'].notnull() &
    df_clean['torque_nm'].isnull()
).sum()

print("Genuinely missing:", genuine_missing)
print("Unparsed values:", unparsed)
print("Total missing torque:", df_clean['torque_nm'].isnull().sum())

Genuinely missing: 209
Unparsed values: 36
Total missing torque: 245

In [297]:
unparsed_torque = df_clean[
    df_clean['torque'].notnull() &
    df_clean['torque_nm'].isnull()
]

unparsed_torque[
    ['name', 'year', 'torque']
]

                                     name  year                     torque
140            Skoda Superb LK 1.8 TSI AT  2018          250@ 1250-5000rpm
604              Tata Sumo CX 10 Str BSIV  2011       115@ 2,500(kgm@ rpm)
951                          Maruti Zen D  2003             789Nm@ 2250rpm
1211                 Maruti SX4 Vxi BSIII  2007       145@ 4,100(kgm@ rpm)
1676  Mercedes-Benz M-Class ML 350 4Matic  2011             510@ 1600-2400
2000     Honda Jazz Select Edition Active  2011            110(11.2)@ 4800
2086          Tata Sumo EX 10/7 Str BSIII  2012       115@ 2,500(kgm@ rpm)
2289                 Maruti SX4 Zxi BSIII  2010       145@ 4,100(kgm@ rpm)
2314    Maruti SX4 Zxi with Leather BSIII  2008       145@ 4,100(kgm@ rpm)
2421                    Ford Ikon 1.6 Nxt  2009        130@ 2500(kgm@ rpm)
2880                Ford Ikon 1.6 EXi NXt  2003        130@ 2500(kgm@ rpm)
4149                 Maruti SX4 Vxi BSIII  2009       145@ 4,100(kgm@ rpm)
4309                 Maruti SX4 Vxi BSIII  2007       145@ 4,100(kgm@ rpm)
4373     Skoda Octavia Classic 1.9 TDI MT  2006                 210 / 1900
4454              Tata Sumo GX 7 Str BSII  2006        115@ 2500(kgm@ rpm)
4629                 Maruti SX4 Zxi BSIII  2009       145@ 4,100(kgm@ rpm)
4720                         Maruti Zen D  2002             789Nm@ 2250rpm
4971                Tata Sumo CX 9 Seater  2008       115@ 2,500(kgm@ rpm)
4987                 Maruti SX4 Zxi BSIII  2010       145@ 4,100(kgm@ rpm)
4996        Mahindra Logan Petrol 1.4 GLE  2010       110@ 3,000(kgm@ rpm)
5029                 Maruti SX4 Vxi BSIII  2008       145@ 4,100(kgm@ rpm)
5143                         Maruti Zen D  2006             789Nm@ 2250rpm
5242          Tata Sumo EX 10/7 Str BSIII  2008       115@ 2,500(kgm@ rpm)
5415                      Tata Sumo EX TC  2005      190@ 21,800(kgm@ rpm)
5572     Skoda Octavia Classic 1.9 TDI MT  2007                 210 / 1900
5635    Maruti SX4 Zxi with Leather BSIII  2008       145@ 4,100(kgm@ rpm)
5785    Skoda Octavia Ambiente 1.9 TDI MT  2007                 210 / 1900
5985                    BMW 5 Series 530d  2013  51@ 1,750-3,000(kgm@ rpm)
6418    Skoda Octavia Ambiente 1.9 TDI MT  2003                 210 / 1900
6597                          BMW X5 3.0d  2008  53@ 2,000-2,750(kgm@ rpm)
6772                    Ford Ikon 1.6 Nxt  2004        130@ 2500(kgm@ rpm)
6918           Ford Ikon 1.6 Really Sport  2003        130@ 2500(kgm@ rpm)
7154       Skoda Octavia Rider 1.9 AT TDI  2008                 210 / 1900
7296       Skoda Octavia Ambiente 1.9 TDI  2010                 210 / 1900
7532    Skoda Octavia Ambiente 1.9 TDI MT  2007                 210 / 1900
7743                 Maruti SX4 Vxi BSIII  2009       145@ 4,100(kgm@ rpm)

In [298]:
def recover_torque(value):

    if pd.isna(value):
        return np.nan

    value = str(value).lower().replace(',', '')

    # Explicitly identified unusual formats
    if re.match(r'^250@', value):
        return 250.0

    if re.match(r'^510@', value):
        return 510.0

    if re.match(r'^110\(11\.2\)@', value):
        return 110.0

    if re.match(r'^210\s*/\s*1900$', value):
        return 210.0

    return np.nan

In [299]:
mask = (
    df_clean['torque'].notna() &
    df_clean['torque_nm'].isna()
)

df_clean.loc[mask, 'torque_nm'] = (
    df_clean.loc[mask, 'torque']
    .apply(recover_torque)
)

In [300]:
remaining = df_clean[
    df_clean['torque'].notna() &
    df_clean['torque_nm'].isna()
]

print("Remaining unparsed records:", len(remaining))

print(remaining['torque'].value_counts())

Remaining unparsed records: 26
torque
145@ 4,100(kgm@ rpm)         10
115@ 2,500(kgm@ rpm)          4
130@ 2500(kgm@ rpm)           4
789Nm@ 2250rpm                3
115@ 2500(kgm@ rpm)           1
110@ 3,000(kgm@ rpm)          1
190@ 21,800(kgm@ rpm)         1
51@ 1,750-3,000(kgm@ rpm)     1
53@ 2,000-2,750(kgm@ rpm)     1
Name: count, dtype: int64

In [301]:
remaining = df_clean[
    df_clean['torque'].notna() &
    df_clean['torque_nm'].isna()
]

remaining[
    ['name', 'year', 'torque']
].sort_values('torque')

                                   name  year                     torque
4996      Mahindra Logan Petrol 1.4 GLE  2010       110@ 3,000(kgm@ rpm)
604            Tata Sumo CX 10 Str BSIV  2011       115@ 2,500(kgm@ rpm)
2086        Tata Sumo EX 10/7 Str BSIII  2012       115@ 2,500(kgm@ rpm)
5242        Tata Sumo EX 10/7 Str BSIII  2008       115@ 2,500(kgm@ rpm)
4971              Tata Sumo CX 9 Seater  2008       115@ 2,500(kgm@ rpm)
4454            Tata Sumo GX 7 Str BSII  2006        115@ 2500(kgm@ rpm)
6772                  Ford Ikon 1.6 Nxt  2004        130@ 2500(kgm@ rpm)
2421                  Ford Ikon 1.6 Nxt  2009        130@ 2500(kgm@ rpm)
2880              Ford Ikon 1.6 EXi NXt  2003        130@ 2500(kgm@ rpm)
6918         Ford Ikon 1.6 Really Sport  2003        130@ 2500(kgm@ rpm)
5635  Maruti SX4 Zxi with Leather BSIII  2008       145@ 4,100(kgm@ rpm)
5029               Maruti SX4 Vxi BSIII  2008       145@ 4,100(kgm@ rpm)
4987               Maruti SX4 Zxi BSIII  2010       145@ 4,100(kgm@ rpm)
7743               Maruti SX4 Vxi BSIII  2009       145@ 4,100(kgm@ rpm)
4309               Maruti SX4 Vxi BSIII  2007       145@ 4,100(kgm@ rpm)
4149               Maruti SX4 Vxi BSIII  2009       145@ 4,100(kgm@ rpm)
2314  Maruti SX4 Zxi with Leather BSIII  2008       145@ 4,100(kgm@ rpm)
2289               Maruti SX4 Zxi BSIII  2010       145@ 4,100(kgm@ rpm)
1211               Maruti SX4 Vxi BSIII  2007       145@ 4,100(kgm@ rpm)
4629               Maruti SX4 Zxi BSIII  2009       145@ 4,100(kgm@ rpm)
5415                    Tata Sumo EX TC  2005      190@ 21,800(kgm@ rpm)
5985                  BMW 5 Series 530d  2013  51@ 1,750-3,000(kgm@ rpm)
6597                        BMW X5 3.0d  2008  53@ 2,000-2,750(kgm@ rpm)
5143                       Maruti Zen D  2006             789Nm@ 2250rpm
951                        Maruti Zen D  2003             789Nm@ 2250rpm
4720                       Maruti Zen D  2002             789Nm@ 2250rpm

In [302]:
# Mahindra Logan 1.4 Petrol
mask_logan = (
    df_clean['name'].str.contains(
        'Mahindra Logan Petrol 1.4', case=False, na=False
    ) &
    df_clean['torque'].str.contains(
        '110@ 3,000', case=False, na=False
    )
)

df_clean.loc[mask_logan, 'torque_nm'] = 110


# Ford Ikon
mask_ford = (
    df_clean['name'].str.contains(
        'Ford Ikon 1.6', case=False, na=False
    ) &
    df_clean['torque'].str.contains(
        '130@ 2500', case=False, na=False
    )
)

df_clean.loc[mask_ford, 'torque_nm'] = 130


# Maruti SX4
mask_sx4 = (
    df_clean['name'].str.contains(
        'Maruti SX4', case=False, na=False
    ) &
    df_clean['torque'].str.contains(
        '145@ 4,100', case=False, na=False
    )
)

df_clean.loc[mask_sx4, 'torque_nm'] = 145

In [303]:
df_clean.loc[
    mask_logan | mask_ford | mask_sx4,
    ['name', 'year', 'torque', 'torque_nm']
]

                                   name  year                torque  torque_nm
1211               Maruti SX4 Vxi BSIII  2007  145@ 4,100(kgm@ rpm)      145.0
2289               Maruti SX4 Zxi BSIII  2010  145@ 4,100(kgm@ rpm)      145.0
2314  Maruti SX4 Zxi with Leather BSIII  2008  145@ 4,100(kgm@ rpm)      145.0
2421                  Ford Ikon 1.6 Nxt  2009   130@ 2500(kgm@ rpm)      130.0
2880              Ford Ikon 1.6 EXi NXt  2003   130@ 2500(kgm@ rpm)      130.0
4149               Maruti SX4 Vxi BSIII  2009  145@ 4,100(kgm@ rpm)      145.0
4309               Maruti SX4 Vxi BSIII  2007  145@ 4,100(kgm@ rpm)      145.0
4629               Maruti SX4 Zxi BSIII  2009  145@ 4,100(kgm@ rpm)      145.0
4987               Maruti SX4 Zxi BSIII  2010  145@ 4,100(kgm@ rpm)      145.0
4996      Mahindra Logan Petrol 1.4 GLE  2010  110@ 3,000(kgm@ rpm)      110.0
5029               Maruti SX4 Vxi BSIII  2008  145@ 4,100(kgm@ rpm)      145.0
5635  Maruti SX4 Zxi with Leather BSIII  2008  145@ 4,100(kgm@ rpm)      145.0
6772                  Ford Ikon 1.6 Nxt  2004   130@ 2500(kgm@ rpm)      130.0
6918         Ford Ikon 1.6 Really Sport  2003   130@ 2500(kgm@ rpm)      130.0
7743               Maruti SX4 Vxi BSIII  2009  145@ 4,100(kgm@ rpm)      145.0

In [304]:
print("Missing torque:",
      df_clean['torque_nm'].isnull().sum())

print("Valid torque:",
      df_clean['torque_nm'].notnull().sum())

Missing torque: 220
Valid torque: 6706

In [305]:
# Original torque was missing
original_missing = df_clean['torque'].isna().sum()

# Original torque existed, but conversion failed
conversion_failed = (
    df_clean['torque'].notna() &
    df_clean['torque_nm'].isna()
).sum()

print("Originally missing torque:", original_missing)
print("Conversion failed:", conversion_failed)
print("Total missing torque:", df_clean['torque_nm'].isna().sum())

Originally missing torque: 209
Conversion failed: 11
Total missing torque: 220

In [306]:
remaining = df_clean[
    df_clean['torque'].notna() &
    df_clean['torque_nm'].isna()
]

print("Remaining records:", len(remaining))

remaining[['name', 'year', 'torque']]

Remaining records: 11

                             name  year                     torque
604      Tata Sumo CX 10 Str BSIV  2011       115@ 2,500(kgm@ rpm)
951                  Maruti Zen D  2003             789Nm@ 2250rpm
2086  Tata Sumo EX 10/7 Str BSIII  2012       115@ 2,500(kgm@ rpm)
4454      Tata Sumo GX 7 Str BSII  2006        115@ 2500(kgm@ rpm)
4720                 Maruti Zen D  2002             789Nm@ 2250rpm
4971        Tata Sumo CX 9 Seater  2008       115@ 2,500(kgm@ rpm)
5143                 Maruti Zen D  2006             789Nm@ 2250rpm
5242  Tata Sumo EX 10/7 Str BSIII  2008       115@ 2,500(kgm@ rpm)
5415              Tata Sumo EX TC  2005      190@ 21,800(kgm@ rpm)
5985            BMW 5 Series 530d  2013  51@ 1,750-3,000(kgm@ rpm)
6597                  BMW X5 3.0d  2008  53@ 2,000-2,750(kgm@ rpm)

In [307]:
missing_percentage = (
    df_clean['torque_nm'].isnull().sum()
    / len(df_clean)
) * 100

print("Missing torque percentage:", round(missing_percentage, 2), "%")

Missing torque percentage: 3.18 %

In [308]:
missing_summary = pd.DataFrame({
    'Missing Values': df_clean.isnull().sum(),
    'Missing Percentage': (
        df_clean.isnull().sum() / len(df_clean)
    ) * 100
})

missing_summary = missing_summary.sort_values(
    by='Missing Percentage',
    ascending=False
)

print(missing_summary)

               Missing Values  Missing Percentage
mileage                   223            3.219752
torque_nm                 220            3.176437
torque                    209            3.017615
max_power                 209            3.017615
seats                     208            3.003176
engine                    208            3.003176
seller_type                 0            0.000000
fuel                        0            0.000000
km_driven                   0            0.000000
selling_price               0            0.000000
year                        0            0.000000
name                        0            0.000000
transmission                0            0.000000
owner                       0            0.000000

In [309]:
# Check original mileage units

print(
    df_clean['mileage']
    .value_counts()
    .head(20)
)

mileage
18.90    210
19.70    168
18.60    150
21.10    147
17.00    124
15.96    108
16.10    106
17.80     96
12.80     88
15.10     86
28.40     85
20.51     83
20.00     83
22.74     80
22.54     76
24.30     73
20.36     71
23.00     71
22.32     71
12.99     70
Name: count, dtype: int64

In [310]:
print(
    df.loc[df_clean.index, 'mileage']
    .str.extract(r'(kmpl|km/kg)', expand=False)
    .value_counts()
)

mileage
kmpl     6631
km/kg      87
Name: count, dtype: int64

In [311]:
# Extract mileage unit from original dataset
df_clean['mileage_unit'] = (
    df.loc[df_clean.index, 'mileage']
    .str.extract(r'(kmpl|km/kg)', expand=False)
)

# Check unit distribution
print(df_clean['mileage_unit'].value_counts(dropna=False))

mileage_unit
kmpl     6631
NaN       208
km/kg      87
Name: count, dtype: int64

In [312]:
# If mileage is missing, its unit should also be missing
df_clean.loc[
    df_clean['mileage'].isna(),
    'mileage_unit'
] = np.nan

# Verify
print(df_clean['mileage_unit'].value_counts(dropna=False))

mileage_unit
kmpl     6616
NaN       223
km/kg      87
Name: count, dtype: int64

In [313]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['mileage_unit'],
    margins=True
)

mileage_unit  km/kg  kmpl   All
fuel
CNG              52     0    52
Diesel            0  3653  3653
LPG              35     0    35
Petrol            0  2963  2963
All              87  6616  6703

In [314]:
# Check unit and fuel consistency

inconsistent = df_clean[
    (
        df_clean['fuel'].isin(['CNG', 'LPG']) &
        (df_clean['mileage_unit'] == 'kmpl')
    ) |
    (
        df_clean['fuel'].isin(['Petrol', 'Diesel']) &
        (df_clean['mileage_unit'] == 'km/kg')
    )
]

print("Inconsistent records:", len(inconsistent))

Inconsistent records: 0

In [315]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['mileage'].isna(),
    margins=True
)

mileage  False  True   All
fuel
CNG         52     4    56
Diesel    3653   102  3755
LPG         35     3    38
Petrol    2963   114  3077
All       6703   223  6926

In [316]:
mileage_median = df_clean.groupby('fuel')['mileage'].median()

print("Median mileage by fuel type:")
print(mileage_median)

Median mileage by fuel type:
fuel
CNG       24.95
Diesel    20.00
LPG       17.30
Petrol    18.90
Name: mileage, dtype: float64

In [317]:
# Fill missing mileage using fuel-wise median
df_clean['mileage'] = df_clean['mileage'].fillna(
    df_clean.groupby('fuel')['mileage'].transform('median')
)

In [318]:
print("Missing mileage after imputation:",
      df_clean['mileage'].isnull().sum())

print("Dataset shape:", df_clean.shape)

Missing mileage after imputation: 0
Dataset shape: (6926, 15)

In [319]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['engine'].isna(),
    margins=True
)

engine  False  True   All
fuel
CNG        52     4    56
Diesel   3658    97  3755
LPG        35     3    38
Petrol   2973   104  3077
All      6718   208  6926

In [320]:
print(
    df_clean.groupby('fuel')['engine'].median()
)

fuel
CNG        998.0
Diesel    1493.0
LPG       1061.0
Petrol    1197.0
Name: engine, dtype: float64

In [321]:
# Fill missing engine values using fuel-wise median
df_clean['engine'] = df_clean['engine'].fillna(
    df_clean.groupby('fuel')['engine'].transform('median')
)

In [322]:
print("Missing engine values:",
      df_clean['engine'].isnull().sum())

print("Dataset shape:", df_clean.shape)

Missing engine values: 0
Dataset shape: (6926, 15)

In [323]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['max_power'].isna(),
    margins=True
)

max_power  False  True   All
fuel
CNG           51     5    56
Diesel      3658    97  3755
LPG           35     3    38
Petrol      2973   104  3077
All         6717   209  6926

In [324]:
print(
    df_clean.groupby('fuel')['max_power'].median()
)

fuel
CNG       61.70
Diesel    88.73
LPG       58.20
Petrol    78.90
Name: max_power, dtype: float64

In [325]:
# Fill missing max_power using fuel-wise median

df_clean['max_power'] = df_clean['max_power'].fillna(
    df_clean.groupby('fuel')['max_power'].transform('median')
)

In [326]:
print("Missing max_power values:",
      df_clean['max_power'].isnull().sum())

print("Dataset shape:", df_clean.shape)

Missing max_power values: 0
Dataset shape: (6926, 15)

In [327]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['seats'].isna(),
    margins=True
)

seats   False  True   All
fuel
CNG        52     4    56
Diesel   3658    97  3755
LPG        35     3    38
Petrol   2973   104  3077
All      6718   208  6926

In [328]:
missing_seats = df_clean[df_clean['seats'].isna()]

print("Missing seat records:", len(missing_seats))

missing_seats[['name', 'year', 'fuel', 'engine']].head(20)

Missing seat records: 208

                                      name  year    fuel  engine
13                    Maruti Swift 1.3 VXi  2007  Petrol  1197.0
31                      Fiat Palio 1.2 ELX  2003  Petrol  1197.0
78                         Tata Indica DLS  2003  Diesel  1493.0
87             Maruti Swift VDI BSIV W ABS  2015  Diesel  1493.0
119                  Maruti Swift VDI BSIV  2010  Diesel  1493.0
138                BMW X1 sDrive 20D xLine  2017  Diesel  1493.0
200                        Toyota Etios GD  2012  Diesel  1493.0
206                Maruti Omni E 8 Str STD  2003  Petrol  1197.0
228                   Maruti Swift 1.3 VXi  2008  Petrol  1197.0
252                        Tata Indica DLS  2005  Diesel  1493.0
306                   Maruti Swift 1.3 VXi  2010  Petrol  1197.0
316              Mahindra Willys CJ 3B 4X4  1983  Diesel  1493.0
336                 Hyundai Santro Xing XL  2005  Petrol  1197.0
390  Toyota Etios Liva Diesel TRD Sportivo  2012  Diesel  1493.0
516                  Maruti Swift VDI BSIV  2010  Diesel  1493.0
535                      Maruti Estilo LXI  2010  Petrol  1197.0
539                  Maruti Swift VDI BSIV  2008  Diesel  1493.0
575                    Maruti Alto K10 LXI  2011  Petrol  1197.0
688                 Hyundai Santro Xing XG  2006  Petrol  1197.0
725                        Toyota Etios GD  2012  Diesel  1493.0

In [329]:
# Count records and known seat values for each vehicle name

seat_by_name = df_clean.groupby('name').agg(
    total_records=('seats', 'size'),
    known_seats=('seats', 'count'),
    median_seats=('seats', 'median')
)

# Find vehicle names having missing seats
missing_name_info = seat_by_name[
    seat_by_name['known_seats'] > 0
]

print(missing_name_info.head(20))

                                      total_records  known_seats  median_seats
name
Ambassador CLASSIC 1500 DSL AC                    1            1           5.0
Ambassador Classic 2000 DSZ AC PS                 1            1           5.0
Ambassador Grand 1500 DSZ BSIII                   1            1           5.0
Ambassador Grand 2000 DSZ PW CL                   1            1           5.0
Ashok Leyland Stile LE                            1            1           8.0
Audi A3 35 TDI Premium Plus                       2            2           5.0
Audi A3 40 TFSI Premium                           1            1           5.0
Audi A4 1.8 TFSI                                  1            1           5.0
Audi A4 2.0 TDI                                   2            2           5.0
Audi A4 2.0 TDI 177 Bhp Premium Plus              1            1           5.0
Audi A4 35 TDI Premium Plus                       4            4           5.0
Audi A6 2.0 TDI                                   1            1           5.0
Audi A6 2.0 TDI  Design Edition                   1            1           5.0
Audi A6 2.0 TDI Premium Plus                      1            1           5.0
Audi A6 2.0 TDI Technology                        1            1           5.0
Audi A6 35 TFSI Matrix                            3            3           5.0
Audi Q3 2.0 TDI Quattro Premium Plus              3            3           5.0
Audi Q3 35 TDI Quattro Premium Plus               1            1           5.0
Audi Q3 35 TDI Quattro Technology                 1            1           5.0
Audi Q5 2.0 TDI                                   1            1           5.0

In [330]:
# Vehicle names with at least one known seat value
known_names = df_clean.groupby('name')['seats'].transform(
    lambda x: x.notna().any()
)

recoverable = (
    df_clean['seats'].isna() & known_names
).sum()

print("Missing seats:", df_clean['seats'].isna().sum())
print("Recoverable using same vehicle name:", recoverable)

Missing seats: 208
Recoverable using same vehicle name: 56

In [331]:
# Calculate median seats for each vehicle name
name_median = df_clean.groupby('name')['seats'].transform('median')

# Identify missing values that can be recovered
mask = df_clean['seats'].isna() & name_median.notna()

# Fill using same vehicle name
df_clean.loc[mask, 'seats'] = name_median[mask]

print("Recovered seat values:", mask.sum())
print("Remaining missing seats:", df_clean['seats'].isna().sum())

Recovered seat values: 56
Remaining missing seats: 152

In [332]:
# Inspect remaining missing seat records

remaining_seats = df_clean[df_clean['seats'].isna()]

print("Remaining records:", len(remaining_seats))

remaining_seats[
    ['name', 'year', 'fuel', 'engine', 'max_power']
].head(30)

Remaining records: 152

                                         name  year    fuel  engine  max_power
13                       Maruti Swift 1.3 VXi  2007  Petrol  1197.0      78.90
31                         Fiat Palio 1.2 ELX  2003  Petrol  1197.0      78.90
78                            Tata Indica DLS  2003  Diesel  1493.0      88.73
87                Maruti Swift VDI BSIV W ABS  2015  Diesel  1493.0      88.73
138                   BMW X1 sDrive 20D xLine  2017  Diesel  1493.0      88.73
228                      Maruti Swift 1.3 VXi  2008  Petrol  1197.0      78.90
252                           Tata Indica DLS  2005  Diesel  1493.0      88.73
306                      Maruti Swift 1.3 VXi  2010  Petrol  1197.0      78.90
316                 Mahindra Willys CJ 3B 4X4  1983  Diesel  1493.0      88.73
336                    Hyundai Santro Xing XL  2005  Petrol  1197.0      78.90
390     Toyota Etios Liva Diesel TRD Sportivo  2012  Diesel  1493.0      88.73
535                         Maruti Estilo LXI  2010  Petrol  1197.0      78.90
688                    Hyundai Santro Xing XG  2006  Petrol  1197.0      78.90
743                      Maruti Swift 1.3 VXi  2006  Petrol  1197.0      78.90
744                       Mahindra Bolero GLX  2004  Diesel  1493.0      88.73
747          Maruti Zen Estilo VXI BSIV W ABS  2011  Petrol  1197.0      78.90
756                    Hyundai Santro Xing XP  2003  Petrol  1197.0      78.90
774             Hyundai Santro GLS I - Euro I  1999  Petrol  1197.0      78.90
776                      Skoda Superb 1.8 TSI  2010  Petrol  1197.0      78.90
862                  Maruti Esteem Vxi - BSII  2005  Petrol  1197.0      78.90
992                      Mahindra Xylo E8 BS4  2010  Diesel  1493.0      88.73
1015                   Fiat Punto 1.3 Emotion  2013  Diesel  1493.0      88.73
1045                   Toyota Qualis Fleet A3  2000  Diesel  1493.0      88.73
1183           Hyundai Santro GLS I - Euro II  2004  Petrol  1197.0      78.90
1184  Hyundai Santro Xing XG AT eRLX Euro III  2004  Petrol  1197.0      78.90
1200         Maruti Zen Estilo VXI BSIV W ABS  2011  Petrol  1197.0      78.90
1210   Maruti Omni BSIII 8-STR W/ IMMOBILISER  2009  Petrol  1197.0      78.90
1216                    Mahindra Jeep Classic  1996  Diesel  1493.0      88.73
1322     Hyundai Santro GS zipDrive - Euro II  2004  Petrol  1197.0      78.90
1331                     Maruti Swift 1.3 VXi  2008  Petrol  1197.0      78.90

In [333]:
# Extract manufacturer and model prefix
df_clean['model_group'] = (
    df_clean['name']
    .str.split()
    .str[:2]
    .str.join(' ')
)

# Calculate median seats for each model group
model_median = (
    df_clean.groupby('model_group')['seats']
    .transform('median')
)

# Identify recoverable missing values
model_mask = (
    df_clean['seats'].isna() &
    model_median.notna()
)

print("Recoverable using model group:", model_mask.sum())

Recoverable using model group: 132

In [334]:
# Check the number of distinct seat configurations
group_check = df_clean.groupby('model_group').agg(
    known_seats=('seats', 'count'),
    different_seat_values=('seats', 'nunique'),
    median_seats=('seats', 'median')
)

# Groups with multiple seating configurations
ambiguous_groups = group_check[
    group_check['different_seat_values'] > 1
]

print("Ambiguous model groups:", len(ambiguous_groups))
print(ambiguous_groups.sort_values(
    'different_seat_values',
    ascending=False
).head(20))

Ambiguous model groups: 24
                        known_seats  different_seat_values  median_seats
model_group
Mahindra Bolero                 183                      4           7.0
Mahindra Scorpio                160                      4           7.0
Tata Sumo                        27                      4           7.0
Chevrolet Tavera                 24                      3           9.5
Mahindra Xylo                    49                      3           8.0
Chevrolet Enjoy                  23                      2           7.0
Chevrolet Cruze                  14                      2           5.0
BMW 3                            14                      2           5.0
Land Rover                        3                      2           5.0
Hyundai Tucson                    2                      2           6.0
Datsun GO                        34                      2           5.0
Mahindra Marazzo                 10                      2           7.0
Mahindra TUV                     52                      2           7.0
Mahindra Thar                    22                      2           6.0
Maruti 800                       89                      2           4.0
Mahindra KUV                     44                      2           6.0
Maruti Alto                     395                      2           5.0
Maruti Eeco                      53                      2           5.0
Mercedes-Benz GL-Class            4                      2           6.0
Maruti Omni                      45                      2           8.0

In [335]:
# Number of distinct seat configurations per model group
group_nunique = (
    df_clean.groupby('model_group')['seats']
    .transform('nunique')
)

# Median seats for each model group
group_median = (
    df_clean.groupby('model_group')['seats']
    .transform('median')
)

# Fill only when the group has exactly one known seat configuration
safe_mask = (
    df_clean['seats'].isna() &
    (group_nunique == 1)
)

print("Safely recoverable records:", safe_mask.sum())
print("Remaining missing records:",
      df_clean['seats'].isna().sum() - safe_mask.sum())

Safely recoverable records: 122
Remaining missing records: 30

In [336]:
# Fill missing seats only where model group has one
# consistent known seat configuration

df_clean.loc[safe_mask, 'seats'] = group_median[safe_mask]

print("Recovered values:", safe_mask.sum())
print("Remaining missing seats:", df_clean['seats'].isna().sum())

Recovered values: 122
Remaining missing seats: 30

In [337]:
remaining_seats = df_clean[df_clean['seats'].isna()]

print("Remaining records:", len(remaining_seats))

remaining_seats[
    ['name', 'year', 'fuel', 'engine', 'max_power']
]

Remaining records: 30

                                        name  year    fuel  engine  max_power
31                        Fiat Palio 1.2 ELX  2003  Petrol  1197.0      78.90
316                Mahindra Willys CJ 3B 4X4  1983  Diesel  1493.0      88.73
535                        Maruti Estilo LXI  2010  Petrol  1197.0      78.90
744                      Mahindra Bolero GLX  2004  Diesel  1493.0      88.73
992                     Mahindra Xylo E8 BS4  2010  Diesel  1493.0      88.73
1210  Maruti Omni BSIII 8-STR W/ IMMOBILISER  2009  Petrol  1197.0      78.90
1216                   Mahindra Jeep Classic  1996  Diesel  1493.0      88.73
1347                   Mahindra Ingenio CRDe  2017  Diesel  1493.0      88.73
1432                Mahindra Jeep CL 500 MDI  1994  Diesel  1493.0      88.73
1815                    Mahindra Jeep MM 540  1995  Diesel  1493.0      88.73
1933                       Maruti Estilo LXI  2010  Petrol  1197.0      78.90
2105                      Tata Sumo EX BS IV  2012  Diesel  1493.0      88.73
2466                Maruti Omni LPG STD BSIV  2008     LPG  1061.0      58.20
2867                Mahindra Jeep MM 550 XDB  2005  Diesel  1493.0      88.73
2959                      Toyota Premio Base  2004  Petrol  1197.0      78.90
3154                      Mahindra Bolero LX  2006  Diesel  1493.0      88.73
3310                         Tata Estate Std  1999  Diesel  1493.0      88.73
3456                 Volkswagen Multivan TDI  2011  Diesel  1493.0      88.73
3922                    Mahindra Jeep MM 540  1998  Diesel  1493.0      88.73
4542                Maruti Omni LPG STD BSIV  1999     LPG  1061.0      58.20
5005                          Fiat Palio 1.2  2006  Petrol  1197.0      78.90
5322                Maruti Omni LPG STD BSIV  1991     LPG  1061.0      58.20
5385                Mahindra Jeep CL 500 MDI  1997  Diesel  1493.0      88.73
5451                     Mahindra Marshal DI  2000  Diesel  1493.0      88.73
5583                      Mahindra Bolero LX  2005  Diesel  1493.0      88.73
6516                       Maruti Estilo LXI  2010  Petrol  1197.0      78.90
6730                         Peugeot 309 GLD  1997  Diesel  1493.0      88.73
6912                     Mahindra Bolero GLX  2006  Diesel  1493.0      88.73
7275                       Maruti Estilo LXI  2009  Petrol  1197.0      78.90
7528                       Maruti Estilo LXI  2008  Petrol  1197.0      78.90

In [338]:
print("Missing seats:", df_clean['seats'].isnull().sum())
print("Dataset shape:", df_clean.shape)

print("\nSeat distribution:")
print(df_clean['seats'].value_counts().sort_index())

Missing seats: 30
Dataset shape: (6926, 16)

Seat distribution:
seats
2.0        2
4.0      124
5.0     5418
6.0       57
7.0      966
8.0      231
9.0       74
10.0      23
14.0       1
Name: count, dtype: int64

In [339]:
pd.crosstab(
    df_clean['fuel'],
    df_clean['torque_nm'].isna(),
    margins=True
)

torque_nm  False  True   All
fuel
CNG           51     5    56
Diesel      3647   108  3755
LPG           35     3    38
Petrol      2973   104  3077
All         6706   220  6926

In [340]:
print(
    df_clean.groupby('fuel')['torque_nm'].median()
)

fuel
CNG        83.0
Diesel    200.0
LPG        77.0
Petrol    109.0
Name: torque_nm, dtype: float64

In [341]:
# Calculate median torque for each exact vehicle name
torque_by_name = (
    df_clean.groupby('name')['torque_nm']
    .transform('median')
)

# Find missing torque values with a known value
# for the same vehicle name
torque_mask = (
    df_clean['torque_nm'].isna() &
    torque_by_name.notna()
)

print("Missing torque:", df_clean['torque_nm'].isna().sum())
print("Recoverable by vehicle name:", torque_mask.sum())

Missing torque: 220
Recoverable by vehicle name: 56

In [342]:
# Count distinct known torque values for each vehicle name
torque_nunique = (
    df_clean.groupby('name')['torque_nm']
    .transform('nunique')
)

# Calculate median torque for each vehicle name
torque_median = (
    df_clean.groupby('name')['torque_nm']
    .transform('median')
)

# Only accept groups with one unique known torque value
safe_torque_mask = (
    df_clean['torque_nm'].isna() &
    (torque_nunique == 1)
)

print("Safely recoverable:",
      safe_torque_mask.sum())

print("Remaining missing:",
      df_clean['torque_nm'].isna().sum()
      - safe_torque_mask.sum())

Safely recoverable: 56
Remaining missing: 164

In [343]:
# Fill missing torque using exact vehicle-name median
df_clean.loc[safe_torque_mask, 'torque_nm'] = (
    torque_median[safe_torque_mask]
)

print("Recovered torque values:", safe_torque_mask.sum())

print(
    "Remaining missing torque:",
    df_clean['torque_nm'].isna().sum()
)

Recovered torque values: 56
Remaining missing torque: 164

In [344]:
remaining_torque = df_clean[
    df_clean['torque_nm'].isna()
]

print("Remaining records:", len(remaining_torque))

remaining_torque[
    ['name', 'year', 'fuel', 'engine', 'max_power']
].head(30)

Remaining records: 164

                                         name  year    fuel  engine  max_power
13                       Maruti Swift 1.3 VXi  2007  Petrol  1197.0      78.90
31                         Fiat Palio 1.2 ELX  2003  Petrol  1197.0      78.90
78                            Tata Indica DLS  2003  Diesel  1493.0      88.73
87                Maruti Swift VDI BSIV W ABS  2015  Diesel  1493.0      88.73
138                   BMW X1 sDrive 20D xLine  2017  Diesel  1493.0      88.73
228                      Maruti Swift 1.3 VXi  2008  Petrol  1197.0      78.90
252                           Tata Indica DLS  2005  Diesel  1493.0      88.73
306                      Maruti Swift 1.3 VXi  2010  Petrol  1197.0      78.90
316                 Mahindra Willys CJ 3B 4X4  1983  Diesel  1493.0      88.73
336                    Hyundai Santro Xing XL  2005  Petrol  1197.0      78.90
390     Toyota Etios Liva Diesel TRD Sportivo  2012  Diesel  1493.0      88.73
535                         Maruti Estilo LXI  2010  Petrol  1197.0      78.90
604                  Tata Sumo CX 10 Str BSIV  2011  Diesel  1948.0      68.00
688                    Hyundai Santro Xing XG  2006  Petrol  1197.0      78.90
743                      Maruti Swift 1.3 VXi  2006  Petrol  1197.0      78.90
744                       Mahindra Bolero GLX  2004  Diesel  1493.0      88.73
747          Maruti Zen Estilo VXI BSIV W ABS  2011  Petrol  1197.0      78.90
756                    Hyundai Santro Xing XP  2003  Petrol  1197.0      78.90
774             Hyundai Santro GLS I - Euro I  1999  Petrol  1197.0      78.90
776                      Skoda Superb 1.8 TSI  2010  Petrol  1197.0      78.90
862                  Maruti Esteem Vxi - BSII  2005  Petrol  1197.0      78.90
951                              Maruti Zen D  2003  Diesel  1527.0      58.00
992                      Mahindra Xylo E8 BS4  2010  Diesel  1493.0      88.73
1015                   Fiat Punto 1.3 Emotion  2013  Diesel  1493.0      88.73
1045                   Toyota Qualis Fleet A3  2000  Diesel  1493.0      88.73
1183           Hyundai Santro GLS I - Euro II  2004  Petrol  1197.0      78.90
1184  Hyundai Santro Xing XG AT eRLX Euro III  2004  Petrol  1197.0      78.90
1200         Maruti Zen Estilo VXI BSIV W ABS  2011  Petrol  1197.0      78.90
1210   Maruti Omni BSIII 8-STR W/ IMMOBILISER  2009  Petrol  1197.0      78.90
1216                    Mahindra Jeep Classic  1996  Diesel  1493.0      88.73

In [345]:
# Count distinct known torque values per model group
torque_group_nunique = (
    df_clean.groupby('model_group')['torque_nm']
    .transform('nunique')
)

# Calculate median torque per model group
torque_group_median = (
    df_clean.groupby('model_group')['torque_nm']
    .transform('median')
)

# Identify missing values in groups with one known torque value
safe_group_mask = (
    df_clean['torque_nm'].isna() &
    (torque_group_nunique == 1)
)

print("Safely recoverable by model group:",
      safe_group_mask.sum())

print("Remaining missing torque:",
      df_clean['torque_nm'].isna().sum()
      - safe_group_mask.sum())

Safely recoverable by model group: 5
Remaining missing torque: 159

In [346]:
# Inspect the 5 candidate records
df_clean.loc[
    safe_group_mask,
    ['name', 'model_group', 'year',
     'fuel', 'engine', 'max_power',
     'torque', 'torque_nm']
]

,name,model_group,year,fuel,engine,max_power,torque,torque_nm
1045,Toyota Qualis Fleet A3,Toyota Qualis,2000,Diesel,1493.0,88.73,NaN,NaN
2271,Toyota Qualis GS G1,Toyota Qualis,2003,Diesel,1493.0,88.73,NaN,NaN
2726,Toyota Qualis GS G1,Toyota Qualis,2002,Diesel,1493.0,88.73,NaN,NaN
4954,Toyota Qualis GS C1,Toyota Qualis,2004,Diesel,1493.0,88.73,NaN,NaN
5060,Toyota Qualis FS F7,Toyota Qualis,2000,Diesel,1493.0,88.73,NaN,NaN